___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<img src=https://i.ibb.co/8NdjfdZ/Num-Py-logo.png width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Session - 01</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:150%; text-align:center; border-radius:10px 10px;">Numpy Arrays (Part-02)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [WHAT NUMPY? & WHY DO WE NEED IT?](#0)
    * [When you make a change to an array, it becomes another object.](#0.1)
    * [Advanced mathematical operations are executed more efficientl](#0.2)
    * [Comparing list and array by size](#0.3)
    * [Comparing list and array by computation time](#0.4)
* [THE END OF THE SESSION-01 (PART-02)](#1)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Why Numpy? & Why Do We Need It?</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**There are several important differences between NumPy arrays and the standard Python sequences:**

- **``NumPy arrays``** have a ``fixed size`` at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a **``NumPy array``** are all required to be of ``the same data type``, and thus will be the ``same size in memory``. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- **``NumPy arrays``** facilitate ``advanced mathematical and other types of operations`` on large numbers of data. Typically, such operations are executed more efficiently and ``with less code`` than is possible using Python's built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today's scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

<img src=https://i.ibb.co/2FD1VMM/Numpy-vs-Lists.pngg width="500" height="200">

[Numpy Array vs List Source 01](https://blog.finxter.com/what-are-advantages-of-numpy-over-regular-python-lists/),
[Numpy Array vs List Source 02](https://numpy.org/doc/stable/user/whatisnumpy.html),
[Numpy Array vs List Source 03](https://python.plainenglish.io/python-list-vs-numpy-array-whats-the-difference-7308cd4b52f6),
[Numpy vs List Source 04](https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference#:~:text=A%20numpy%20array%20is%20a,a%20tuple%20of%20nonnegative%20integers.&text=A%20list%20is%20the%20Python,contain%20elements%20of%20different%20types.),
[Numpy Array vs List Source 05](https://dev.to/chanduthedev/python-list-vs-numpy-array-3pjp),
[Numpy Array vs List Source 06](https://medium.com/analytics-vidhya/list-vs-numpy-comparision-35bf921588e9),
[Numpy Array vs List Source 07](https://stackoverflow.com/questions/15944171/python-differences-between-lists-and-numpy-array-of-objects),
[Numpy Array vs List Video Source 01](https://www.youtube.com/watch?v=mkbgEvUkSaM),
[Numpy Array vs List Video Source 02](https://www.youtube.com/watch?v=JtW_xGNDEJ8),
[Numpy Array vs List Video Source 03](https://www.youtube.com/watch?v=C10KmAbCW6A)

In [1]:
import numpy as np
import time
import sys

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">When you make a change to an array, it becomes another object!</p>

<a id="0.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [2]:
my_list = [1, 2, 3, 4, 5]

my_first_array = np.array(my_list)
my_first_array

array([1, 2, 3, 4, 5])

In [3]:
id(my_first_array)  # this is the location of my_first_array in memory.

2489391605520

In [4]:
id(np.append(my_first_array, (6, 7)))   # the location of array changed.
                                        # this is a different array object now.

2489391678608

**let's look at the same situation for the lists in Python:**

In [5]:
id(my_list)  # this is the location of my_list in memory.

2489391504768

In [6]:
my_list.append([6, 7])  # we have added some values to the list.
my_list

[1, 2, 3, 4, 5, [6, 7]]

In [7]:
id(my_list)  # Be noted! The location of my_list didn't change.
             # Unlike numpy arrays, it is still the same object!

2489391504768

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Advanced mathematical operations are executed more efficiently</p>

<a id="0.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [8]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

In [9]:
# a * b # Gives an error

In [10]:
a_mult_b = []

for i in range(len(a)) :
    a_mult_b.append(a[i] * b[i])
    
a_mult_b

[2, 6, 12, 20]

**let's do the same in the numpy arrays:**

In [11]:
a_arr = np.array(a)
b_arr = np.array(b)

In [12]:
a_arr * b_arr

array([ 2,  6, 12, 20])

**Another example:**

In [13]:
a1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [2, 3, 4, 5]])
b1 = np.array([[2, 3, 4, 5], [1, 2, 4, 5], [1, 2, 3, 4]])

In [14]:
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [15]:
b1

array([[2, 3, 4, 5],
       [1, 2, 4, 5],
       [1, 2, 3, 4]])

In [16]:
a1 * b1

array([[ 2,  6, 12, 20],
       [ 1,  4, 12, 20],
       [ 2,  6, 12, 20]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Comparing list and array by size</p>

<a id="0.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [17]:
sys.getsizeof(5)  # Return the size of object in bytes.

28

In [18]:
sys.getsizeof(99999999)

28

In [19]:
sys.getsizeof("a")

50

In [20]:
sys.getsizeof("alidelveli")

59

In [21]:
l = range(1000)

print("size of one item in list :", sys.getsizeof(5)) 
print("size of all item in list :", sys.getsizeof(5) * len(l))

print("---" * 10)

a = np.arange(1000)

print("size of one item in array :", a.itemsize)
print("size of all items in array :", a.itemsize * a.size )

size of one item in list : 28
size of all item in list : 28000
------------------------------
size of one item in array : 4
size of all items in array : 4000


### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Comparing list and array by computation time</p>

<a id="0.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [22]:
time.time()  # Return the current time in seconds since the Epoch.

1659271477.0620122

In [23]:
start = time.time()  # Assigning the current epoch time to the "start" variable
start

1659271477.1786206

In [24]:
# Wait for several seconds and than run this cell. 

time.time() - start  # time difference between two operations

0.07572269439697266

In [25]:
size = 1000000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

#python list
start = time.time()
result = [(x + y) for x, y in zip(l1, l2)]
print("python list took: ", (time.time()-start) * 1000)

# numpy array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time() - start) * 1000)

python list took:  371.3676929473877
numpy took:  24.25217628479004


## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of the NumPy Session-01 (Part-02)</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___